### ISSUE TITLE
Constrain edges are not applied correctly

### ISSUE THREAD

**Issue by kochizufan** [kninnug/Constrainautor#6]
I used this library in my code like this:

https://github.com/code4history/MaplatTin/blob/delaunay/src/constrained-tin.ts

But in this result, constrained edges are not correctly applied.

I included data files (points, constrained edges and result triangles) in attached zip

[points_edges_triangles.zip](https://github.com/kninnug/Constrainautor/files/8790883/points_edges_triangles.zip)

And I attached visualized result: You can see blue triangle edge is crossing over red constrained edge:

![error](https://user-images.githubusercontent.com/2221431/170819708-007b6842-9be0-467e-b483-e0c6e407faa5.png)
 
Can you check this data case?

**Comment by kninnug** [comment]
I see that in the [constrained-tin.ts](https://github.com/code4history/MaplatTin/blob/delaunay/src/constrained-tin.ts) file, you're calling `con.delaunify(true)`, but not `con.constrainAll(edges)` (or `con.constrainOne` for each edge), so the edges won't actually be constrained.
Does the issue still happen when you do call this method?

**Comment by kochizufan** [comment]
Thank you, I confirmed it was my mistake.
Sorry ,
